DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS sessions;
