version: "3"

volumes:
  dbbackups:
  postgis-data:

services:
  main_service:
    image: main_service
    ports:
      - "8080:8080"
    env_file:
      - envs/golang.env
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - postgres

  auth:
    image: auth_service
    env_file:
      - envs/golang.env
    ports:
      - "8081:8081"
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - postgres

  comment:
    image: comment_service
    env_file:
      - envs/golang.env
    ports:
      - "8082:8082"
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - postgres

  postgres:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - $PWD/docker/migrations/up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"