version: "3"

volumes:
  dbbackups:
  postgis-data:

services:
  main_service:
    image: main_service
    ports:
      - "8080:8080"
    volumes:
      - $PWD/static:/app/static
    depends_on:
      - postgres

  auth:
    image: auth_service
    ports:
      - "8081:8081"
    volumes:
      - $PWD/static:/app/static
    depends_on:
      - postgres

  comment:
    image: comment_service
    ports:
      - "8082:8082"
    volumes:
      - $PWD/static:/app/static
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - $PWD/docker/migrations/up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - envs/postgres.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"