// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/microservices/authorization (interfaces: AuthUsecase)

package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockAuthUsecase is a mock of AuthUsecase interface
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return _m.recorder
}

// CheckSession mocks base method
func (_m *MockAuthUsecase) CheckSession(_param0 context.Context, _param1 string) (models.User, error) {
	ret := _m.ctrl.Call(_m, "CheckSession", _param0, _param1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSession indicates an expected call of CheckSession
func (_mr *MockAuthUsecaseMockRecorder) CheckSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckSession", reflect.TypeOf((*MockAuthUsecase)(nil).CheckSession), arg0, arg1)
}

// Login mocks base method
func (_m *MockAuthUsecase) Login(_param0 context.Context, _param1 models.LoginData) (string, error) {
	ret := _m.ctrl.Call(_m, "Login", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login
func (_mr *MockAuthUsecaseMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Login", reflect.TypeOf((*MockAuthUsecase)(nil).Login), arg0, arg1)
}

// Logout mocks base method
func (_m *MockAuthUsecase) Logout(_param0 context.Context, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Logout", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout
func (_mr *MockAuthUsecaseMockRecorder) Logout(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Logout", reflect.TypeOf((*MockAuthUsecase)(nil).Logout), arg0, arg1)
}
