// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/microservices/authorization (interfaces: AuthRepository)

package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockAuthRepository is a mock of AuthRepository interface
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return _m.recorder
}

// CheckUser mocks base method
func (_m *MockAuthRepository) CheckUser(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "CheckUser", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckUser indicates an expected call of CheckUser
func (_mr *MockAuthRepositoryMockRecorder) CheckUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckUser", reflect.TypeOf((*MockAuthRepository)(nil).CheckUser), arg0)
}

// CheckUserBySession mocks base method
func (_m *MockAuthRepository) CheckUserBySession(_param0 string) string {
	ret := _m.ctrl.Call(_m, "CheckUserBySession", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

// CheckUserBySession indicates an expected call of CheckUserBySession
func (_mr *MockAuthRepositoryMockRecorder) CheckUserBySession(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckUserBySession", reflect.TypeOf((*MockAuthRepository)(nil).CheckUserBySession), arg0)
}

// DeleteSession mocks base method
func (_m *MockAuthRepository) DeleteSession(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteSession", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession
func (_mr *MockAuthRepositoryMockRecorder) DeleteSession(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DeleteSession", reflect.TypeOf((*MockAuthRepository)(nil).DeleteSession), arg0)
}

// InsertSession mocks base method
func (_m *MockAuthRepository) InsertSession(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "InsertSession", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession
func (_mr *MockAuthRepositoryMockRecorder) InsertSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InsertSession", reflect.TypeOf((*MockAuthRepository)(nil).InsertSession), arg0, arg1)
}

// SelectImages mocks base method
func (_m *MockAuthRepository) SelectImages(_param0 int) ([]string, error) {
	ret := _m.ctrl.Call(_m, "SelectImages", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectImages indicates an expected call of SelectImages
func (_mr *MockAuthRepositoryMockRecorder) SelectImages(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectImages", reflect.TypeOf((*MockAuthRepository)(nil).SelectImages), arg0)
}

// SelectUser mocks base method
func (_m *MockAuthRepository) SelectUser(_param0 string) (models.User, error) {
	ret := _m.ctrl.Call(_m, "SelectUser", _param0)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUser indicates an expected call of SelectUser
func (_mr *MockAuthRepositoryMockRecorder) SelectUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectUser", reflect.TypeOf((*MockAuthRepository)(nil).SelectUser), arg0)
}

// SelectUserBySession mocks base method
func (_m *MockAuthRepository) SelectUserBySession(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "SelectUserBySession", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserBySession indicates an expected call of SelectUserBySession
func (_mr *MockAuthRepositoryMockRecorder) SelectUserBySession(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectUserBySession", reflect.TypeOf((*MockAuthRepository)(nil).SelectUserBySession), arg0)
}
