// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/microservices/comments/delivery/grpc/client (interfaces: CommentClientInterface)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockCommentClientInterface is a mock of CommentClientInterface interface
type MockCommentClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommentClientInterfaceMockRecorder
}

// MockCommentClientInterfaceMockRecorder is the mock recorder for MockCommentClientInterface
type MockCommentClientInterfaceMockRecorder struct {
	mock *MockCommentClientInterface
}

// NewMockCommentClientInterface creates a new mock instance
func NewMockCommentClientInterface(ctrl *gomock.Controller) *MockCommentClientInterface {
	mock := &MockCommentClientInterface{ctrl: ctrl}
	mock.recorder = &MockCommentClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommentClientInterface) EXPECT() *MockCommentClientInterfaceMockRecorder {
	return m.recorder
}

// Comment mocks base method
func (m *MockCommentClientInterface) Comment(arg0 context.Context, arg1 models.User, arg2 models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment
func (mr *MockCommentClientInterfaceMockRecorder) Comment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockCommentClientInterface)(nil).Comment), arg0, arg1, arg2)
}

// CommentsByID mocks base method
func (m *MockCommentClientInterface) CommentsByID(arg0 context.Context, arg1 int) (models.CommentsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentsByID", arg0, arg1)
	ret0, _ := ret[0].(models.CommentsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentsByID indicates an expected call of CommentsByID
func (mr *MockCommentClientInterfaceMockRecorder) CommentsByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentsByID", reflect.TypeOf((*MockCommentClientInterface)(nil).CommentsByID), arg0, arg1)
}
