// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/microservices/comments/delivery/grpc/client (interfaces: CommentClientInterface)

package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockCommentClientInterface is a mock of CommentClientInterface interface
type MockCommentClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommentClientInterfaceMockRecorder
}

// MockCommentClientInterfaceMockRecorder is the mock recorder for MockCommentClientInterface
type MockCommentClientInterfaceMockRecorder struct {
	mock *MockCommentClientInterface
}

// NewMockCommentClientInterface creates a new mock instance
func NewMockCommentClientInterface(ctrl *gomock.Controller) *MockCommentClientInterface {
	mock := &MockCommentClientInterface{ctrl: ctrl}
	mock.recorder = &MockCommentClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCommentClientInterface) EXPECT() *MockCommentClientInterfaceMockRecorder {
	return _m.recorder
}

// Comment mocks base method
func (_m *MockCommentClientInterface) Comment(_param0 context.Context, _param1 models.User, _param2 models.Comment) error {
	ret := _m.ctrl.Call(_m, "Comment", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment
func (_mr *MockCommentClientInterfaceMockRecorder) Comment(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Comment", reflect.TypeOf((*MockCommentClientInterface)(nil).Comment), arg0, arg1, arg2)
}

// CommentsByID mocks base method
func (_m *MockCommentClientInterface) CommentsByID(_param0 context.Context, _param1 int) (models.CommentsData, error) {
	ret := _m.ctrl.Call(_m, "CommentsByID", _param0, _param1)
	ret0, _ := ret[0].(models.CommentsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentsByID indicates an expected call of CommentsByID
func (_mr *MockCommentClientInterfaceMockRecorder) CommentsByID(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CommentsByID", reflect.TypeOf((*MockCommentClientInterface)(nil).CommentsByID), arg0, arg1)
}
