// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/api/chats (interfaces: ChatUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockChatUsecase is a mock of ChatUsecase interface
type MockChatUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChatUsecaseMockRecorder
}

// MockChatUsecaseMockRecorder is the mock recorder for MockChatUsecase
type MockChatUsecaseMockRecorder struct {
	mock *MockChatUsecase
}

// NewMockChatUsecase creates a new mock instance
func NewMockChatUsecase(ctrl *gomock.Controller) *MockChatUsecase {
	mock := &MockChatUsecase{ctrl: ctrl}
	mock.recorder = &MockChatUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChatUsecase) EXPECT() *MockChatUsecaseMockRecorder {
	return m.recorder
}

// Chat mocks base method
func (m *MockChatUsecase) Chat(arg0 models.Chat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chat indicates an expected call of Chat
func (mr *MockChatUsecaseMockRecorder) Chat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockChatUsecase)(nil).Chat), arg0)
}

// ChatID mocks base method
func (m *MockChatUsecase) ChatID(arg0 models.User, arg1 int) (models.ChatData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatID", arg0, arg1)
	ret0, _ := ret[0].(models.ChatData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatID indicates an expected call of ChatID
func (mr *MockChatUsecaseMockRecorder) ChatID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatID", reflect.TypeOf((*MockChatUsecase)(nil).ChatID), arg0, arg1)
}

// Chats mocks base method
func (m *MockChatUsecase) Chats(arg0 models.User) (models.ChatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chats", arg0)
	ret0, _ := ret[0].(models.ChatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chats indicates an expected call of Chats
func (mr *MockChatUsecaseMockRecorder) Chats(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chats", reflect.TypeOf((*MockChatUsecase)(nil).Chats), arg0)
}

// CheckSession mocks base method
func (m *MockChatUsecase) CheckSession(arg0 context.Context, arg1 []*http.Cookie) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", arg0, arg1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSession indicates an expected call of CheckSession
func (mr *MockChatUsecaseMockRecorder) CheckSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockChatUsecase)(nil).CheckSession), arg0, arg1)
}

// Dislike mocks base method
func (m *MockChatUsecase) Dislike(arg0 models.User, arg1 models.Dislike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dislike", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dislike indicates an expected call of Dislike
func (mr *MockChatUsecaseMockRecorder) Dislike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dislike", reflect.TypeOf((*MockChatUsecase)(nil).Dislike), arg0, arg1)
}

// Like mocks base method
func (m *MockChatUsecase) Like(arg0 models.User, arg1 models.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like
func (mr *MockChatUsecaseMockRecorder) Like(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockChatUsecase)(nil).Like), arg0, arg1)
}

// MatchUser mocks base method
func (m *MockChatUsecase) MatchUser(arg0 models.User, arg1 models.Like) (models.Chat, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchUser", arg0, arg1)
	ret0, _ := ret[0].(models.Chat)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MatchUser indicates an expected call of MatchUser
func (mr *MockChatUsecaseMockRecorder) MatchUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchUser", reflect.TypeOf((*MockChatUsecase)(nil).MatchUser), arg0, arg1)
}

// Message mocks base method
func (m *MockChatUsecase) Message(arg0 models.User, arg1 models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Message indicates an expected call of Message
func (mr *MockChatUsecaseMockRecorder) Message(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockChatUsecase)(nil).Message), arg0, arg1)
}

// Msg mocks base method
func (m *MockChatUsecase) Msg(arg0 models.User, arg1 models.Msg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Msg", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Msg indicates an expected call of Msg
func (mr *MockChatUsecaseMockRecorder) Msg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Msg", reflect.TypeOf((*MockChatUsecase)(nil).Msg), arg0, arg1)
}

// Partner mocks base method
func (m *MockChatUsecase) Partner(arg0 models.User, arg1 int) (models.UserFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Partner", arg0, arg1)
	ret0, _ := ret[0].(models.UserFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Partner indicates an expected call of Partner
func (mr *MockChatUsecaseMockRecorder) Partner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Partner", reflect.TypeOf((*MockChatUsecase)(nil).Partner), arg0, arg1)
}

// Sessions mocks base method
func (m *MockChatUsecase) Sessions(arg0 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sessions indicates an expected call of Sessions
func (mr *MockChatUsecaseMockRecorder) Sessions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockChatUsecase)(nil).Sessions), arg0)
}

// Superlike mocks base method
func (m *MockChatUsecase) Superlike(arg0 models.User, arg1 models.Superlike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Superlike", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Superlike indicates an expected call of Superlike
func (mr *MockChatUsecaseMockRecorder) Superlike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Superlike", reflect.TypeOf((*MockChatUsecase)(nil).Superlike), arg0, arg1)
}

// User mocks base method
func (m *MockChatUsecase) User(arg0 string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", arg0)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User
func (mr *MockChatUsecaseMockRecorder) User(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockChatUsecase)(nil).User), arg0)
}

// UserFeed mocks base method
func (m *MockChatUsecase) UserFeed(arg0 string) (models.UserFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFeed", arg0)
	ret0, _ := ret[0].(models.UserFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFeed indicates an expected call of UserFeed
func (mr *MockChatUsecaseMockRecorder) UserFeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFeed", reflect.TypeOf((*MockChatUsecase)(nil).UserFeed), arg0)
}
