// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/api/users (interfaces: UserRepository)

package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
	time "time"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return _m.recorder
}

// CheckPremium mocks base method
func (_m *MockUserRepository) CheckPremium(_param0 int) bool {
	ret := _m.ctrl.Call(_m, "CheckPremium", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPremium indicates an expected call of CheckPremium
func (_mr *MockUserRepositoryMockRecorder) CheckPremium(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckPremium", reflect.TypeOf((*MockUserRepository)(nil).CheckPremium), arg0)
}

// CheckSuperLikeMe mocks base method
func (_m *MockUserRepository) CheckSuperLikeMe(_param0 int, _param1 int) bool {
	ret := _m.ctrl.Call(_m, "CheckSuperLikeMe", _param0, _param1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckSuperLikeMe indicates an expected call of CheckSuperLikeMe
func (_mr *MockUserRepositoryMockRecorder) CheckSuperLikeMe(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckSuperLikeMe", reflect.TypeOf((*MockUserRepository)(nil).CheckSuperLikeMe), arg0, arg1)
}

// CheckUser mocks base method
func (_m *MockUserRepository) CheckUser(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "CheckUser", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckUser indicates an expected call of CheckUser
func (_mr *MockUserRepositoryMockRecorder) CheckUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CheckUser", reflect.TypeOf((*MockUserRepository)(nil).CheckUser), arg0)
}

// DeleteSession mocks base method
func (_m *MockUserRepository) DeleteSession(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteSession", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession
func (_mr *MockUserRepositoryMockRecorder) DeleteSession(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DeleteSession", reflect.TypeOf((*MockUserRepository)(nil).DeleteSession), arg0)
}

// InsertPremium mocks base method
func (_m *MockUserRepository) InsertPremium(_param0 int, _param1 time.Time, _param2 time.Time) error {
	ret := _m.ctrl.Call(_m, "InsertPremium", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPremium indicates an expected call of InsertPremium
func (_mr *MockUserRepositoryMockRecorder) InsertPremium(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InsertPremium", reflect.TypeOf((*MockUserRepository)(nil).InsertPremium), arg0, arg1, arg2)
}

// InsertSession mocks base method
func (_m *MockUserRepository) InsertSession(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "InsertSession", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession
func (_mr *MockUserRepositoryMockRecorder) InsertSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InsertSession", reflect.TypeOf((*MockUserRepository)(nil).InsertSession), arg0, arg1)
}

// InsertUser mocks base method
func (_m *MockUserRepository) InsertUser(_param0 models.User) error {
	ret := _m.ctrl.Call(_m, "InsertUser", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser
func (_mr *MockUserRepositoryMockRecorder) InsertUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InsertUser", reflect.TypeOf((*MockUserRepository)(nil).InsertUser), arg0)
}

// SelectImages mocks base method
func (_m *MockUserRepository) SelectImages(_param0 int) ([]string, error) {
	ret := _m.ctrl.Call(_m, "SelectImages", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectImages indicates an expected call of SelectImages
func (_mr *MockUserRepositoryMockRecorder) SelectImages(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectImages", reflect.TypeOf((*MockUserRepository)(nil).SelectImages), arg0)
}

// SelectUserByID mocks base method
func (_m *MockUserRepository) SelectUserByID(_param0 int) (models.User, error) {
	ret := _m.ctrl.Call(_m, "SelectUserByID", _param0)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserByID indicates an expected call of SelectUserByID
func (_mr *MockUserRepositoryMockRecorder) SelectUserByID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectUserByID", reflect.TypeOf((*MockUserRepository)(nil).SelectUserByID), arg0)
}

// SelectUserFeedByID mocks base method
func (_m *MockUserRepository) SelectUserFeedByID(_param0 int) (models.UserFeed, error) {
	ret := _m.ctrl.Call(_m, "SelectUserFeedByID", _param0)
	ret0, _ := ret[0].(models.UserFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserFeedByID indicates an expected call of SelectUserFeedByID
func (_mr *MockUserRepositoryMockRecorder) SelectUserFeedByID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectUserFeedByID", reflect.TypeOf((*MockUserRepository)(nil).SelectUserFeedByID), arg0)
}

// SelectUsers mocks base method
func (_m *MockUserRepository) SelectUsers(_param0 models.User) ([]models.UserFeed, error) {
	ret := _m.ctrl.Call(_m, "SelectUsers", _param0)
	ret0, _ := ret[0].([]models.UserFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUsers indicates an expected call of SelectUsers
func (_mr *MockUserRepositoryMockRecorder) SelectUsers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectUsers", reflect.TypeOf((*MockUserRepository)(nil).SelectUsers), arg0)
}

// UpdateUser mocks base method
func (_m *MockUserRepository) UpdateUser(_param0 models.User, _param1 int) error {
	ret := _m.ctrl.Call(_m, "UpdateUser", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser
func (_mr *MockUserRepositoryMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), arg0, arg1)
}
