global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: ['127.0.0.1:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093