global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: ['95.163.213.222:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['95.163.213.222:9100']

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093