// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/users/delivery/grpc/protobuf/user.proto

// protoc --go_out=plugins=grpc:. *.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Telephone string `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginData) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *LoginData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sess string `protobuf:"bytes,1,opt,name=sess,proto3" json:"sess,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetSess() string {
	if x != nil {
		return x.Sess
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserID) Reset() {
	*x = UserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Telephone  string   `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Password   string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DateBirth  int32    `protobuf:"varint,5,opt,name=date_birth,json=dateBirth,proto3" json:"date_birth,omitempty"`
	Sex        string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	LinkImages []string `protobuf:"bytes,7,rep,name=linkImages,proto3" json:"linkImages,omitempty"`
	Job        string   `protobuf:"bytes,8,opt,name=job,proto3" json:"job,omitempty"`
	Education  string   `protobuf:"bytes,9,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe    string   `protobuf:"bytes,10,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetDateBirth() int32 {
	if x != nil {
		return x.DateBirth
	}
	return 0
}

func (x *User) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *User) GetLinkImages() []string {
	if x != nil {
		return x.LinkImages
	}
	return nil
}

func (x *User) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *User) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *User) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

type UserFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateBirth  int32    `protobuf:"varint,3,opt,name=date_birth,json=dateBirth,proto3" json:"date_birth,omitempty"`
	LinkImages []string `protobuf:"bytes,4,rep,name=linkImages,proto3" json:"linkImages,omitempty"`
	Job        string   `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Education  string   `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe    string   `protobuf:"bytes,7,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
}

func (x *UserFeed) Reset() {
	*x = UserFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeed) ProtoMessage() {}

func (x *UserFeed) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeed.ProtoReflect.Descriptor instead.
func (*UserFeed) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserFeed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFeed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserFeed) GetDateBirth() int32 {
	if x != nil {
		return x.DateBirth
	}
	return 0
}

func (x *UserFeed) GetLinkImages() []string {
	if x != nil {
		return x.LinkImages
	}
	return nil
}

func (x *UserFeed) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UserFeed) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *UserFeed) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

type UserMe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Telephone  string   `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	DateBirth  int32    `protobuf:"varint,4,opt,name=date_birth,json=dateBirth,proto3" json:"date_birth,omitempty"`
	LinkImages []string `protobuf:"bytes,5,rep,name=linkImages,proto3" json:"linkImages,omitempty"`
	Job        string   `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Education  string   `protobuf:"bytes,7,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe    string   `protobuf:"bytes,8,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
}

func (x *UserMe) Reset() {
	*x = UserMe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMe) ProtoMessage() {}

func (x *UserMe) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMe.ProtoReflect.Descriptor instead.
func (*UserMe) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserMe) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMe) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UserMe) GetDateBirth() int32 {
	if x != nil {
		return x.DateBirth
	}
	return 0
}

func (x *UserMe) GetLinkImages() []string {
	if x != nil {
		return x.LinkImages
	}
	return nil
}

func (x *UserMe) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UserMe) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *UserMe) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserRequest) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type SettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *User `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SettingsRequest) Reset() {
	*x = SettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsRequest) ProtoMessage() {}

func (x *SettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsRequest.ProtoReflect.Descriptor instead.
func (*SettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{7}
}

func (x *SettingsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SettingsRequest) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserMeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UserMe `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserMeResponse) Reset() {
	*x = UserMeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMeResponse) ProtoMessage() {}

func (x *UserMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMeResponse.ProtoReflect.Descriptor instead.
func (*UserMeResponse) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserMeResponse) GetData() *UserMe {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UserFeed `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserFeedResponse) Reset() {
	*x = UserFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedResponse) ProtoMessage() {}

func (x *UserFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedResponse.ProtoReflect.Descriptor instead.
func (*UserFeedResponse) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserFeedResponse) GetData() *UserFeed {
	if x != nil {
		return x.Data
	}
	return nil
}

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy bool `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{11}
}

func (x *Nothing) GetDummy() bool {
	if x != nil {
		return x.Dummy
	}
	return false
}

type UserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UserID `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserIDRequest) GetData() *UserID {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_users_delivery_grpc_protobuf_user_proto protoreflect.FileDescriptor

var file_api_users_delivery_grpc_protobuf_user_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1d, 0x0a, 0x07, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x73, 0x73, 0x22, 0x18, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xff, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x4d, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65,
	0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x22,
	0xd3, 0x01, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x4d, 0x65, 0x22, 0x2d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x10, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x22, 0x31, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x95, 0x03, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x52, 0x50, 0x43, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x06, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12,
	0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x02, 0x4d, 0x65, 0x12, 0x0d, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x14, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x11, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x2b, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_users_delivery_grpc_protobuf_user_proto_rawDescOnce sync.Once
	file_api_users_delivery_grpc_protobuf_user_proto_rawDescData = file_api_users_delivery_grpc_protobuf_user_proto_rawDesc
)

func file_api_users_delivery_grpc_protobuf_user_proto_rawDescGZIP() []byte {
	file_api_users_delivery_grpc_protobuf_user_proto_rawDescOnce.Do(func() {
		file_api_users_delivery_grpc_protobuf_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_users_delivery_grpc_protobuf_user_proto_rawDescData)
	})
	return file_api_users_delivery_grpc_protobuf_user_proto_rawDescData
}

var file_api_users_delivery_grpc_protobuf_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_users_delivery_grpc_protobuf_user_proto_goTypes = []interface{}{
	(*LoginData)(nil),        // 0: user.LoginData
	(*Session)(nil),          // 1: user.Session
	(*UserID)(nil),           // 2: user.UserID
	(*User)(nil),             // 3: user.User
	(*UserFeed)(nil),         // 4: user.UserFeed
	(*UserMe)(nil),           // 5: user.UserMe
	(*UserRequest)(nil),      // 6: user.UserRequest
	(*SettingsRequest)(nil),  // 7: user.SettingsRequest
	(*UserResponse)(nil),     // 8: user.UserResponse
	(*UserMeResponse)(nil),   // 9: user.UserMeResponse
	(*UserFeedResponse)(nil), // 10: user.UserFeedResponse
	(*Nothing)(nil),          // 11: user.Nothing
	(*UserIDRequest)(nil),    // 12: user.UserIDRequest
}
var file_api_users_delivery_grpc_protobuf_user_proto_depIdxs = []int32{
	3,  // 0: user.UserRequest.data:type_name -> user.User
	3,  // 1: user.SettingsRequest.data:type_name -> user.User
	3,  // 2: user.UserResponse.data:type_name -> user.User
	5,  // 3: user.UserMeResponse.data:type_name -> user.UserMe
	4,  // 4: user.UserFeedResponse.data:type_name -> user.UserFeed
	2,  // 5: user.UserIDRequest.data:type_name -> user.UserID
	0,  // 6: user.UserGRPCHandler.Login:input_type -> user.LoginData
	1,  // 7: user.UserGRPCHandler.Logout:input_type -> user.Session
	6,  // 8: user.UserGRPCHandler.Signup:input_type -> user.UserRequest
	7,  // 9: user.UserGRPCHandler.Settings:input_type -> user.SettingsRequest
	1,  // 10: user.UserGRPCHandler.Me:input_type -> user.Session
	6,  // 11: user.UserGRPCHandler.Feed:input_type -> user.UserRequest
	12, // 12: user.UserGRPCHandler.UserID:input_type -> user.UserIDRequest
	1,  // 13: user.UserGRPCHandler.User:input_type -> user.Session
	8,  // 14: user.UserGRPCHandler.Login:output_type -> user.UserResponse
	11, // 15: user.UserGRPCHandler.Logout:output_type -> user.Nothing
	11, // 16: user.UserGRPCHandler.Signup:output_type -> user.Nothing
	11, // 17: user.UserGRPCHandler.Settings:output_type -> user.Nothing
	9,  // 18: user.UserGRPCHandler.Me:output_type -> user.UserMeResponse
	10, // 19: user.UserGRPCHandler.Feed:output_type -> user.UserFeedResponse
	10, // 20: user.UserGRPCHandler.UserID:output_type -> user.UserFeedResponse
	8,  // 21: user.UserGRPCHandler.User:output_type -> user.UserResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_users_delivery_grpc_protobuf_user_proto_init() }
func file_api_users_delivery_grpc_protobuf_user_proto_init() {
	if File_api_users_delivery_grpc_protobuf_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nothing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_users_delivery_grpc_protobuf_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_users_delivery_grpc_protobuf_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_delivery_grpc_protobuf_user_proto_goTypes,
		DependencyIndexes: file_api_users_delivery_grpc_protobuf_user_proto_depIdxs,
		MessageInfos:      file_api_users_delivery_grpc_protobuf_user_proto_msgTypes,
	}.Build()
	File_api_users_delivery_grpc_protobuf_user_proto = out.File
	file_api_users_delivery_grpc_protobuf_user_proto_rawDesc = nil
	file_api_users_delivery_grpc_protobuf_user_proto_goTypes = nil
	file_api_users_delivery_grpc_protobuf_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserGRPCHandlerClient is the client API for UserGRPCHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserGRPCHandlerClient interface {
	Login(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*UserResponse, error)
	Logout(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Nothing, error)
	Signup(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Nothing, error)
	Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*Nothing, error)
	Me(ctx context.Context, in *Session, opts ...grpc.CallOption) (*UserMeResponse, error)
	Feed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserFeedResponse, error)
	UserID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserFeedResponse, error)
	User(ctx context.Context, in *Session, opts ...grpc.CallOption) (*UserResponse, error)
}

type userGRPCHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGRPCHandlerClient(cc grpc.ClientConnInterface) UserGRPCHandlerClient {
	return &userGRPCHandlerClient{cc}
}

func (c *userGRPCHandlerClient) Login(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) Logout(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) Signup(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Settings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) Me(ctx context.Context, in *Session, opts ...grpc.CallOption) (*UserMeResponse, error) {
	out := new(UserMeResponse)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Me", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) Feed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserFeedResponse, error) {
	out := new(UserFeedResponse)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/Feed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) UserID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserFeedResponse, error) {
	out := new(UserFeedResponse)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/UserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCHandlerClient) User(ctx context.Context, in *Session, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserGRPCHandler/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGRPCHandlerServer is the server API for UserGRPCHandler service.
type UserGRPCHandlerServer interface {
	Login(context.Context, *LoginData) (*UserResponse, error)
	Logout(context.Context, *Session) (*Nothing, error)
	Signup(context.Context, *UserRequest) (*Nothing, error)
	Settings(context.Context, *SettingsRequest) (*Nothing, error)
	Me(context.Context, *Session) (*UserMeResponse, error)
	Feed(context.Context, *UserRequest) (*UserFeedResponse, error)
	UserID(context.Context, *UserIDRequest) (*UserFeedResponse, error)
	User(context.Context, *Session) (*UserResponse, error)
}

// UnimplementedUserGRPCHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedUserGRPCHandlerServer struct {
}

func (*UnimplementedUserGRPCHandlerServer) Login(context.Context, *LoginData) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) Logout(context.Context, *Session) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) Signup(context.Context, *UserRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) Settings(context.Context, *SettingsRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Settings not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) Me(context.Context, *Session) (*UserMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Me not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) Feed(context.Context, *UserRequest) (*UserFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) UserID(context.Context, *UserIDRequest) (*UserFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserID not implemented")
}
func (*UnimplementedUserGRPCHandlerServer) User(context.Context, *Session) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}

func RegisterUserGRPCHandlerServer(s *grpc.Server, srv UserGRPCHandlerServer) {
	s.RegisterService(&_UserGRPCHandler_serviceDesc, srv)
}

func _UserGRPCHandler_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Login(ctx, req.(*LoginData))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Logout(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Signup(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_Settings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Settings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Settings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Settings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Me",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Me(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/Feed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).Feed(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_UserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).UserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/UserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).UserID(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPCHandler_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCHandlerServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserGRPCHandler/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCHandlerServer).User(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserGRPCHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserGRPCHandler",
	HandlerType: (*UserGRPCHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserGRPCHandler_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserGRPCHandler_Logout_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _UserGRPCHandler_Signup_Handler,
		},
		{
			MethodName: "Settings",
			Handler:    _UserGRPCHandler_Settings_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _UserGRPCHandler_Me_Handler,
		},
		{
			MethodName: "Feed",
			Handler:    _UserGRPCHandler_Feed_Handler,
		},
		{
			MethodName: "UserID",
			Handler:    _UserGRPCHandler_UserID_Handler,
		},
		{
			MethodName: "User",
			Handler:    _UserGRPCHandler_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/users/delivery/grpc/protobuf/user.proto",
}
