[all]
  type = "Debug"
  port = "80" 
  serviceName = "miami"

[SQLDataBase]
  Server = "95.163.213.222"
  Database = "miami"
  ApplicationName = "service"
  MaxIdleConns = 2
  MaxOpenConns = 2
  ConnMaxLifetime = "5m"

[ServerOpt]
  ReadTimeout = "5s"
  WriteTimeout = "5s"
  IdleTimeout = "5s"
