// Code generated by MockGen. DO NOT EDIT.
// Source: park_2020/2020_2_tmp_name/microservices/authorization/delivery/grpc/client (interfaces: AuthClientInterface)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	models "park_2020/2020_2_tmp_name/models"
	reflect "reflect"
)

// MockAuthClientInterface is a mock of AuthClientInterface interface
type MockAuthClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientInterfaceMockRecorder
}

// MockAuthClientInterfaceMockRecorder is the mock recorder for MockAuthClientInterface
type MockAuthClientInterfaceMockRecorder struct {
	mock *MockAuthClientInterface
}

// NewMockAuthClientInterface creates a new mock instance
func NewMockAuthClientInterface(ctrl *gomock.Controller) *MockAuthClientInterface {
	mock := &MockAuthClientInterface{ctrl: ctrl}
	mock.recorder = &MockAuthClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthClientInterface) EXPECT() *MockAuthClientInterfaceMockRecorder {
	return m.recorder
}

// CheckSession mocks base method
func (m *MockAuthClientInterface) CheckSession(arg0 context.Context, arg1 []*http.Cookie) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", arg0, arg1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSession indicates an expected call of CheckSession
func (mr *MockAuthClientInterfaceMockRecorder) CheckSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockAuthClientInterface)(nil).CheckSession), arg0, arg1)
}

// Login mocks base method
func (m *MockAuthClientInterface) Login(arg0 context.Context, arg1 *models.LoginData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login
func (mr *MockAuthClientInterfaceMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthClientInterface)(nil).Login), arg0, arg1)
}

// Logout mocks base method
func (m *MockAuthClientInterface) Logout(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout
func (mr *MockAuthClientInterfaceMockRecorder) Logout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthClientInterface)(nil).Logout), arg0, arg1)
}
