# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_features.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_features.proto',
  package='face_features',
  syntax='proto3',
  serialized_options=b'Z\017.;face_features',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66\x61\x63\x65_features.proto\x12\rface_features\"#\n\x05Photo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04mask\x18\x02 \x01(\t\"\x14\n\x04\x46\x61\x63\x65\x12\x0c\n\x04have\x18\x01 \x01(\x08\x32\x83\x01\n\x0f\x46\x61\x63\x65GRPCHandler\x12\x37\n\x08HaveFace\x12\x14.face_features.Photo\x1a\x13.face_features.Face\"\x00\x12\x37\n\x07\x41\x64\x64Mask\x12\x14.face_features.Photo\x1a\x14.face_features.Photo\"\x00\x42\x11Z\x0f.;face_featuresb\x06proto3'
)




_PHOTO = _descriptor.Descriptor(
  name='Photo',
  full_name='face_features.Photo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='face_features.Photo.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='face_features.Photo.mask', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=73,
)


_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='face_features.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='have', full_name='face_features.Face.have', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Photo'] = _PHOTO
DESCRIPTOR.message_types_by_name['Face'] = _FACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Photo = _reflection.GeneratedProtocolMessageType('Photo', (_message.Message,), {
  'DESCRIPTOR' : _PHOTO,
  '__module__' : 'face_features_pb2'
  # @@protoc_insertion_point(class_scope:face_features.Photo)
  })
_sym_db.RegisterMessage(Photo)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
  'DESCRIPTOR' : _FACE,
  '__module__' : 'face_features_pb2'
  # @@protoc_insertion_point(class_scope:face_features.Face)
  })
_sym_db.RegisterMessage(Face)


DESCRIPTOR._options = None

_FACEGRPCHANDLER = _descriptor.ServiceDescriptor(
  name='FaceGRPCHandler',
  full_name='face_features.FaceGRPCHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=98,
  serialized_end=229,
  methods=[
  _descriptor.MethodDescriptor(
    name='HaveFace',
    full_name='face_features.FaceGRPCHandler.HaveFace',
    index=0,
    containing_service=None,
    input_type=_PHOTO,
    output_type=_FACE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddMask',
    full_name='face_features.FaceGRPCHandler.AddMask',
    index=1,
    containing_service=None,
    input_type=_PHOTO,
    output_type=_PHOTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEGRPCHANDLER)

DESCRIPTOR.services_by_name['FaceGRPCHandler'] = _FACEGRPCHANDLER

# @@protoc_insertion_point(module_scope)
