# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import face_features_pb2 as face__features__pb2


class FaceGRPCHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HaveFace = channel.unary_unary(
                '/face_features.FaceGRPCHandler/HaveFace',
                request_serializer=face__features__pb2.Photo.SerializeToString,
                response_deserializer=face__features__pb2.Face.FromString,
                )
        self.AddMask = channel.unary_unary(
                '/face_features.FaceGRPCHandler/AddMask',
                request_serializer=face__features__pb2.Photo.SerializeToString,
                response_deserializer=face__features__pb2.Photo.FromString,
                )


class FaceGRPCHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HaveFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceGRPCHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HaveFace': grpc.unary_unary_rpc_method_handler(
                    servicer.HaveFace,
                    request_deserializer=face__features__pb2.Photo.FromString,
                    response_serializer=face__features__pb2.Face.SerializeToString,
            ),
            'AddMask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMask,
                    request_deserializer=face__features__pb2.Photo.FromString,
                    response_serializer=face__features__pb2.Photo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_features.FaceGRPCHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceGRPCHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HaveFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_features.FaceGRPCHandler/HaveFace',
            face__features__pb2.Photo.SerializeToString,
            face__features__pb2.Face.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_features.FaceGRPCHandler/AddMask',
            face__features__pb2.Photo.SerializeToString,
            face__features__pb2.Photo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
