name: Docker Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test with cover
        run: make tests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          sudo docker build -t dependencies -f docker/builder.Dockerfile .
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/main_service:latest -f docker/main.Dockerfile .
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:latest -f docker/auth.Dockerfile .
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/comment_service:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/comment_service:latest -f docker/comment.Dockerfile .
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/face_service:${GITHUB_SHA::8} -t ${{ secrets.DOCKERHUB_USERNAME }}/face_service:latest -f docker/face.Dockerfile .
      - name: Push the images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/comment_service:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/face_service:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker images
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/comment_service:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/face_service:${GITHUB_SHA::8}
      - name: Run project
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: docker rm -vf $(docker ps -a -q) || true && cd 2020_2_tmp_name/ && docker-compose up -d --build --no-deps
